# Generated by Django 5.0.6 on 2024-05-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iutapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_of_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
    ]
