# Generated by Django 5.0.6 on 2024-05-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iutapp', '0002_alter_contact_date_of_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='personnel/')),
                ('qualite', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_post'], 'verbose_name': 'Information'},
        ),
    ]
