# Generated by Django 5.0.6 on 2024-05-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iutapp', '0003_personnel_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(upload_to='iutapp/'),
        ),
    ]
