# Generated by Django 5.0.6 on 2024-05-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iutapp', '0004_alter_personnel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(upload_to='iut/'),
        ),
    ]
